### ISSUE TITLE
File : woz_to_csp.py missing

### ISSUE THREAD

**Issue by nitishymtpl** [stanford-oval/CSP-DST#1]
Hi,

Great work! It seems woz_to_csp.py file is missing in CSP-DST repo. Please check it.

python3 woz_to_csp.py --input_folder ../RiSAWOZ/RiSAWOZ-data/task2-data-DST/ --output_folder dataset/risawoz/ --experiment risawoz --ontology_folder ../RiSAWOZ/RiSAWOZ-data/RiSAWOZ-Database-and-Ontology/Ontology/

**Comment by vasu018** [comment]
@Mehrad0711 Could you please kindly take a look into above issue about the missing file **woz_to_csp.py**.

**Comment by Mehrad0711** [comment]
Hi @nitishymtpl and @vasu018,

You need to download the RiSAWOZ dataset and ontology files from their repository: https://github.com/terryqj0107/RiSAWOZ/tree/master/RiSAWOZ-data

**Comment by Mehrad0711** [comment]
Hi @nitishymtpl and @vasu018,

Thanks for reporting this issue! I just committed the missing file.

**Comment by vasu018** [comment]
@Mehrad0711 Thanks a lot for your prompt response. Much appreciated.
